# Generated by Django 3.2.15 on 2022-10-03 07:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_hide_phone_number'),
        ('twilioapp', '0002_auto_20220604_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tokenn',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='twilioapp.basemodel')),
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(blank=True)),
                ('token', models.CharField(db_index=True, max_length=128)),
                ('token_type', models.CharField(choices=[('ForgetPassword', 'ForgetPassword'), ('EmailVerify', 'EmailVerification'), ('TeamInvitation', 'TeamInvitation'), ('OrganizationInvitation', 'OrganizationInvitation'), ('MobileVerify', 'MobileVerification')], max_length=25)),
                ('is_used', models.BooleanField(default=False)),
                ('specification', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='user_management.user')),
            ],
            options={
                'ordering': ('-creation_time',),
            },
            bases=('twilioapp.basemodel',),
        ),
    ]
